import { ICELAND_SUMMER_BOOKING_EXCLUSIONS } from "./iceland-summer-booking-exclusions";
import type { PricingConfig } from "./types";

const SLM_IMAGE = (file: string, width = 1200) =>
  `https://www.senlinmao.com/images/g_auto,f_auto,c_fill,w_${width},q_auto:good/${file}`;

const SLM_CAR_IMAGE = (file: string, width = 1200) =>
  `https://www.senlinmao.com/images/g_auto,f_auto,c_fill,w_${width},q_auto:good/${file}`;

const CORIVO_INSTANCE_ID =
  process.env.CORIVO_CLIENT_ID ?? "ae034790-70dd-4df5-93a0-957be2883176";

export const icelandSelfDriveSummer4Pricing: PricingConfig = {
  packageId: "iceland-self-drive-summer-4",
  currency: "ISK",
  depositRate: 0.2,
  occupancyBase: 2,
  minAdults: 1,
  maxTravelers: 9,
  maxInfants: 2,
  bookingDateRange: { min: "2026-09-10", max: "2027-10-31" },
  bookingDateExclusions: ICELAND_SUMMER_BOOKING_EXCLUSIONS,
  tripDurationDays: 4,
  accommodationIntro:
    "在帕芬假期的套餐中，住宿包含經濟型、舒適型、品質型，跟團套餐僅首都地區住宿可選等級，自駕套餐均可選等級，各等級住宿均含免費 WiFi 及每日早餐，其中經濟型住宿為公共衛浴。",
  vehicleIntro:
    "帕芬假期租車的最低年齡限制為 23 歲（SUV、越野車、商務旅行車）和 20 歲（其他小型轎車）。租車前，您需持有有效駕照至少一年，並提供國內駕照的英文版翻譯公證文件和國際駕照。取車時，請出示這些文件和主駕駛人名下的信用卡（美國運通卡、萬事達卡和 VISA 卡）以支付押金。",
  ageBands: {
    childMultiplier: 0.75,
    infantMultiplier: 0,
  },
  corivo: {
    instanceId: CORIVO_INSTANCE_ID,
    packageTourId: 82174,
    classifications: {
      budget: 9,
      comfort: 1,
      quality: 8,
    },
    vehicleItems: {
      edmn: 62708,
      cdan: 62703,
      cfmn: 62704,
      ifai: 62702,
      ifar: 62705,
      ffar: 62701,
      fmdn: 79441,
      gfar: 126155,
    },
    baseVehicleTier: "edmn",
  },
  tiers: [
    {
      id: "budget",
      label: "經濟型",
      description: "民宿或同等級住宿標準（公共衛浴）",
      perPersonDouble: 0,
      singleSupplementPerNight: 0,
      nights: 3,
      imageUrl: SLM_IMAGE("guesthouse5_fb5c982add.jpg"),
      modalTitle: "關於經濟型房型",
      paragraphs: [
        "民宿或同等級住宿標準，僅含基礎的房間設施，包含公共衛浴，免費 WiFi，每日早餐。如果您的預算有限，經濟型將是一個不錯的選擇。",
        "注意：跟團套餐僅可選擇雷克雅維克地區的住宿等級，非首都區域的住宿等級僅限自駕套餐自由選擇。",
        "經濟型示例飯店：Guesthouse Aurora、Efstidalur Farm、Snorri Guesthouse、Skjaldarvík Guesthouse 等。",
      ],
      galleryImages: [
        SLM_IMAGE("_bf970f5aa3.png"),
        SLM_IMAGE("guesthouse6_2846348eba.jpg"),
        SLM_IMAGE("guesthouse1_86f555c0df.jpg"),
        SLM_IMAGE("guesthouse3_48d49f3f9a.jpg"),
        SLM_IMAGE("guesthouse4_d120be780e.jpg"),
        SLM_IMAGE("guesthouse2_4d91b851fb.jpg"),
      ],
    },
    {
      id: "comfort",
      label: "舒適型",
      description: "三星或同等級住宿標準（私人衛浴）",
      perPersonDouble: 0,
      singleSupplementPerNight: 0,
      nights: 3,
      imageUrl: SLM_IMAGE("hotelvarmaland1_66062887a3.jpg"),
      modalTitle: "關於舒適型房型",
      paragraphs: [
        "套餐內預設的住宿類型。三星級飯店或同等住宿標準，完善的飯店設施，包含獨立衛浴，免費 WiFi，每日早餐。舒適型住宿能夠滿足大多數旅客的住宿標準和需求，是我們推薦的住宿等級。",
        "注意：跟團套餐僅可選擇雷克雅維克地區的住宿等級，非首都區域的住宿等級僅限自駕套餐自由選擇。",
        "舒適型示例飯店：",
        "首都雷克雅維克地區：Hótel Klettur、Fosshótel Lind、Skuggi Hótel、Reykjavík Lights 等。",
        "非首都雷克雅維克地區：Hótel Selfoss、Hótel Katla、Fosshótel Núpar、Fosshotel Vatnajökull、Seljavellir、Selhótel、Berjaya Iceland Hotels、Hótel Varmaland、Fosshótel Reykholt 等。",
      ],
      galleryImages: [
        SLM_IMAGE("lights1_99b9eac460.webp"),
        SLM_IMAGE("lights3_7699e613c2.webp"),
        SLM_IMAGE("hotelvarmaland4_8a9652a9b7.jpg"),
        SLM_IMAGE("fosshotel_baron_breakfast_room_2_0fea55b8be.webp"),
        SLM_IMAGE("fh_reykholt_bar_1_f820fd48cf.webp"),
        SLM_IMAGE("fh_reykholt_restaurant_78fdbdac11.webp"),
        SLM_IMAGE("hotelvarmaland2_3bcf4be056.jpg"),
        SLM_IMAGE("lights2_e40bf4f0bb.webp"),
      ],
    },
    {
      id: "quality",
      label: "品質型",
      description: "四星或同等級輕奢型住宿（私人衛浴）",
      perPersonDouble: 0,
      singleSupplementPerNight: 0,
      nights: 3,
      imageUrl: SLM_IMAGE("sand_hotel_86aa7b195d.webp"),
      modalTitle: "關於品質型房型",
      paragraphs: [
        "四星級飯店或該地區特色精品飯店：完善的飯店設施，包含獨立衛浴，免費 WiFi，早餐。選擇品質型住宿會幫您預訂比舒適型飯店更優質的飯店，或舒適型飯店中更高等級的房型，住宿空間更加寬敞舒適，視野更好。品質型住宿適合預算充足，並對住宿有較高要求的旅客。",
        "注意：跟團套餐僅可選擇雷克雅維克地區的住宿等級，非首都區域的住宿等級僅限自駕套餐自由選擇。",
        "品質型示例飯店：",
        "首都雷克雅維克地區：Alda Hótel、Fosshótel Reykjavík、Exeter、Reykjavík Marina、Hótel Óðinsvé 等。",
        "非首都雷克雅維克地區：Hótel Geysir、Fosshótel Austfirðir、Landhótel、Stracta Hótel、Hótel Kría、Magma hótel、Fosshótel Glacier Lagoon、Hérað、1001 Nótt、Hótel Laxá、Sigló Hotel、Berjaya Iceland Hotels、Hótel KEA、Fosshótel Stykkishólmur 等。",
      ],
      galleryImages: [
        SLM_IMAGE("skuggi_1_f16c0bb950.webp"),
        SLM_IMAGE("siglo2_55fa59cb76.webp"),
        SLM_IMAGE("sand3_0adf8b1446.webp"),
        SLM_IMAGE("skuggi_2_3b94f9f39f.webp"),
        SLM_IMAGE("siglo1_bd8532f504.webp"),
        SLM_IMAGE("sand_4c6d84ccd9.webp"),
        SLM_IMAGE("glacier_lagoon_interior_3_ff57b9af40.webp"),
        SLM_IMAGE("glacier_lagoon_bar_1_3436a3d9bf.webp"),
      ],
    },
  ],
  vehicleTiers: [
    {
      id: "edmn",
      acriss: "EDMN",
      label: "Toyota Yaris | 豐田雅力士",
      description: "緊湊型轎車",
      footnote: "Toyota Yaris | 豐田雅力士 或同級車型",
      imageUrl: SLM_CAR_IMAGE("type_a_y_car_jpg_2b28a93232_8ebb53b2d5.webp"),
      co2Emission: 109,
      gearType: "manual",
      addonTotal: 0,
      seats: 4,
      doors: 5,
      luggage: 1,
    },
    {
      id: "cdan",
      acriss: "CDAN",
      label: "Volkswagen Golf | 福斯高爾夫",
      description: "緊湊型轎車",
      footnote: "Volkswagen Golf | 福斯高爾夫 或同級車型",
      imageUrl: SLM_CAR_IMAGE("type_b2_car_e11097fe32_b9c62e637b.jpg"),
      co2Emission: 273,
      gearType: "automatic",
      addonTotal: 7554,
      seats: 5,
      doors: 5,
      luggage: 1,
    },
    {
      id: "cfmn",
      acriss: "CFMN",
      label: "Dacia Duster 4×4 | 達西亞",
      description: "緊湊型 SUV",
      footnote: "Dacia Duster 4×4 | 達西亞 或同級車型",
      imageUrl: SLM_CAR_IMAGE("type_e2_car_jpg_e28fb4b18e_d965102095.webp"),
      co2Emission: 116,
      gearType: "manual",
      addonTotal: 11794,
      seats: 5,
      doors: 5,
      luggage: 3,
    },
    {
      id: "ifai",
      acriss: "IFAI",
      label: "Hyundai Tucson Hybrid 4×4 | 現代途勝",
      description: "中型 SUV",
      footnote: "Hyundai Tucson Hybrid 4×4 | 現代途勝 或同級車型",
      imageUrl: SLM_CAR_IMAGE("type_r3_car_jpg_a123239eaa_0e1f9cba05.webp"),
      co2Emission: 130,
      co2Note: "插電式油電混合車型",
      gearType: "automatic",
      addonTotal: 20294,
      seats: 5,
      doors: 5,
      luggage: 3,
    },
    {
      id: "ifar",
      acriss: "IFAR",
      label: "Kia Sportage 4×4 | 起亞獅跑",
      description: "緊湊型 SUV",
      footnote: "Kia Sportage 4×4 | 起亞獅跑 或同級車型",
      imageUrl: SLM_CAR_IMAGE("IFMN_632x422_96ced8b8ab.jpg"),
      co2Emission: 176,
      gearType: "automatic",
      addonTotal: 30199,
      seats: 5,
      doors: 5,
      luggage: 3,
    },
    {
      id: "fmdn",
      acriss: "FMDN",
      label: "Volkswagen Caravelle 4×4 | 商務旅行車",
      description: "商務旅行車",
      footnote: "Volkswagen Caravelle 4×4 | 商務旅行車 或同級車型",
      imageUrl: SLM_CAR_IMAGE("type_d1_car_jpg_436d097507_c9912bb228.webp"),
      co2Emission: 198,
      gearType: "automatic",
      addonTotal: 79752,
      seats: 9,
      doors: 5,
      luggage: 7,
    },
    {
      id: "gfar",
      acriss: "GFAR",
      label: "Toyota Land Cruiser 250 4×4 | 豐田陸地巡洋艦",
      description: "大型越野車",
      footnote: "Toyota Land Cruiser 250 4×4 | 豐田陸地巡洋艦 或同級車型",
      imageUrl: SLM_CAR_IMAGE("landcruiser_250_4_X4_6ac9a258f8.png"),
      co2Emission: 251,
      gearType: "automatic",
      addonTotal: 81167,
      seats: 5,
      doors: 5,
      luggage: 5,
    },
    {
      id: "ffar",
      acriss: "FFAR",
      label: "Toyota Land Cruiser 4×4 | 豐田陸地巡洋艦",
      description: "大型越野車",
      footnote: "Toyota Land Cruiser 4×4 | 豐田陸地巡洋艦 或同級車型",
      imageUrl: SLM_CAR_IMAGE("type_i_car_jpg_3dd0fcb29d_856ca531a1.webp"),
      co2Emission: 213,
      gearType: "automatic",
      addonTotal: 0,
      seats: 5,
      doors: 5,
      luggage: 5,
    },
  ],
};
