import type { PricingConfig } from "./types";

const CORIVO_INSTANCE_ID =
  process.env.CORIVO_CLIENT_ID ?? "ae034790-70dd-4df5-93a0-957be2883176";

export const icelandSelfDriveWinter4Pricing: PricingConfig = {
  packageId: "iceland-self-drive-winter-4",
  currency: "ISK",
  depositRate: 0.2,
  occupancyBase: 2,
  minAdults: 1,
  bookingDateRange: { min: "2026-11-01", max: "2027-03-31" },
  tripDurationDays: 4,
  accommodationIntro:
    "在大樂旅行社的套餐中，住宿包含經濟型、舒適型、品質型，跟團套餐僅首都地區住宿可選等級，自駕套餐均可選等級，各等級住宿均含免費 WiFi 及每日早餐，其中經濟型住宿為公共衛浴。",
  vehicleIntro:
    "大樂旅行社租車的最低年齡限制為 23 歲（SUV、越野車、商務旅行車）和 20 歲（其他小型轎車）。租車前，您需持有有效駕照至少一年，並提供國內駕照的英文版翻譯公證文件和國際駕照。取車時，請出示這些文件和主駕駛人名下的信用卡（美國運通卡、萬事達卡和 VISA 卡）以支付押金。",
  ageBands: {
    childMultiplier: 0.75,
    infantMultiplier: 0,
  },
  corivo: {
    instanceId: CORIVO_INSTANCE_ID,
    packageTourId: 82175,
    classifications: {
      budget: 9,
      comfort: 1,
      quality: 8,
    },
    vehicleItems: {
      cfmn: 62761,
      ifai: 62764,
      ifar: 62762,
      ifmn: 62760,
      fmdn: 79442,
      gfar: 126154,
      ffar: 62763,
    },
    baseVehicleTier: "cfmn",
  },
  tiers: [
    {
      id: "budget",
      label: "經濟型",
      description: "民宿或同等級住宿標準（公共衛浴）",
      perPersonDouble: 0,
      singleSupplementPerNight: 0,
      nights: 3,
    },
    {
      id: "comfort",
      label: "舒適型",
      description: "三星或同等級住宿標準（私人衛浴）",
      perPersonDouble: 0,
      singleSupplementPerNight: 0,
      nights: 3,
    },
    {
      id: "quality",
      label: "品質型",
      description: "四星或同等級輕奢型住宿（私人衛浴）",
      perPersonDouble: 0,
      singleSupplementPerNight: 0,
      nights: 3,
    },
  ],
  vehicleTiers: [
    {
      id: "cfmn",
      acriss: "CFMN",
      label: "Dacia Duster 4×4 | 達西亞",
      description: "緊湊型 SUV",
      footnote: "Dacia Duster 4×4 | 達西亞 或同級車型",
      co2Emission: 116,
      gearType: "manual",
      addonTotal: 0,
    },
    {
      id: "ifai",
      acriss: "IFAI",
      label: "Hyundai Tucson Hybrid 4×4 | 現代途勝",
      description: "中型 SUV",
      footnote: "Hyundai Tucson Hybrid 4×4 | 現代途勝 或同級車型",
      co2Emission: 130,
      co2Note: "插電式油電混合車型",
      gearType: "automatic",
      addonTotal: 6602,
    },
    {
      id: "ifar",
      acriss: "IFAR",
      label: "Kia Sportage 4×4 | 起亞獅跑",
      description: "緊湊型 SUV",
      footnote: "Kia Sportage 4×4 | 起亞獅跑 或同級車型",
      co2Emission: 176,
      gearType: "automatic",
      addonTotal: 14151,
    },
    {
      id: "ifmn",
      acriss: "IFMN",
      label: "Kia Sportage 4×4 | 起亞獅跑",
      description: "緊湊型 SUV",
      footnote: "Kia Sportage 4×4 | 起亞獅跑 或同級車型",
      co2Emission: 176,
      gearType: "manual",
      addonTotal: 11321,
    },
    {
      id: "fmdn",
      acriss: "FMDN",
      label: "Volkswagen Caravelle 4×4 | 商務旅行車",
      description: "商務旅行車",
      footnote: "Volkswagen Caravelle 4×4 | 商務旅行車 或同級車型",
      co2Emission: 198,
      gearType: "automatic",
      addonTotal: 75029,
    },
    {
      id: "gfar",
      acriss: "GFAR",
      label: "Toyota Land Cruiser 250 4×4 | 豐田陸地巡洋艦",
      description: "大型越野車",
      footnote: "Toyota Land Cruiser 250 4×4 | 豐田陸地巡洋艦 或同級車型",
      co2Emission: 251,
      gearType: "automatic",
      addonTotal: 54734,
    },
    {
      id: "ffar",
      acriss: "FFAR",
      label: "Toyota Land Cruiser 4×4 | 豐田陸地巡洋艦",
      description: "大型越野車",
      footnote: "Toyota Land Cruiser 4×4 | 豐田陸地巡洋艦 或同級車型",
      co2Emission: 213,
      gearType: "automatic",
      addonTotal: 0,
    },
  ],
};
